# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :beta do
    ensure_git_status_clean
    increment_build_number
    build_app(project: "Nio.xcodeproj", scheme: "Nio")
    upload_to_testflight(
        skip_waiting_for_build_processing: true
    )
end

after_all do |lane|
    notification(message: "finished lane '#{lane}'", open: "http://appstoreconnect.apple.com")
end
